Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
====================== RESTART: C:\Python34\evroopt.py ======================
166
225
375
491
501
749
820
1173
1174
1192
1228
1230
1247
1259
1302
1303
1331
1344
1354
1356
1358
1370
1424
1602
1684
1735
1779
1780
1914
1937
1964
2117
2188
2232
2258
2261
2268
2287
2344
2456
2649
2691
2696
2698
2706
2708
3066
3155
3183
3190
3210
3345
3349
3436
3461
3484
3485
3515
3518
3578
3595
3665
3855
4190
4279
4365
4378
4381
4403
4407
4416
4481
4488
4591
4593
4595
4598
4706
4774
5261
5586
5587
5589
5649
5713
5808
5811
6033
6034
6197
6207
6373
6445
6594
6782
6783
6812
6813
6899
6900
6905
7369
7370
7443
7445
7477
7479
7484
7634
7735
7797
7868
7982
8021
8022
8033
8046
8047
8048
8053
8061
8122
8128
8129
8130
8131
8133
8134
8198
8307
8564
8646
8650
8735
8746
8816
8947
8949
8952
9268
9269
9270
9271
9314
9567
9568
9749
9818
9848
9851
9852
9993
10054
10145
10223
10482
10483
10545
10589
10610
10647
10655
10847
10848
10862
10973
11065
11073
11088
11658
11711
11720
11766
12004
12006
12007
12013
12014
12018
12066
12075
12077
12078
12079
12081
12082
12083
12084
12085
12087
12096
12098
12103
12104
12196
12197
12213
12249
12261
12545
12610
12670
12671
12693
12766
12784
12968
13148
13221
13291
13299
13385
13390
13419
13484
13485
13673
13722
13732
13795
13804
13809
13933
14004
14014
14025
14029
14044
14058
14066
14090
14113
14126
14135
14309
14310
14311
14428
14501
14592
14628
14747
14753
14802
15069
15176
15282
15317
15339
15464
15513
15555
15718
15774
15887
15944
16173
16229
16351
16354
16356
16357
16362
16477
16673
16749
16774
16796
16861
17098
17187
17355
17396
17657
17709
17722
17725
17816
18196
18284
18418
18516
18594
18756
18757
18758
18791
18809
18865
18868
18977
19002
19013
19019
19047
19151
19660
19689
19703
19754
19788
19805
19807
19821
19822
19850
19963
20007
20033
20084
20089
20096
20098
20132
20166
20177
20180
20251
20291
20603
20714
20715
20716
20717
20722
20809
20959
21080
21081
21178
21298
21300
21352
21355
21357
21363
21373
21386
21424
21425
21430
21443
21456
21486
21561
21573
21660
21835
22009
22023
22039
22173
22174
22268
22343
22781
22943
23020
23042
23078
23191
23193
23200
23201
23387
23390
23547
23699
23730
23883
23909
24003
24282
24352
24541
24580
24628
24643
24693
24694
24761
24834
24868
24869
24871
24897
25033
25042
25062
25070
25085
25092
25196
25218
25245
25309
25328
25430
25533
25933
26005
26007
26012
26013
26020
26021
26036
26043
26062
26072
26073
26107
26125
26127
26132
26201
26240
26447
26449
26451
26458
26521
26545
26554
27004
27054
27062
27116
27207
27221
27224
27225
27367
27369
27495
27579
27810
27811
27813
27820
27821
27836
28013
28014
28026
28159
28370
28495
28596
28598
28619
28776
28824
28826
28974
28984
29011
29083
29147
29419
29442
29747
29749
29751
29956
30035
30053
30059
30072
30232
30306
30307
30443
30459
30721
30729
30743
30775
30827
30857
30858
30920
30921
31045
31048
31069
31070
31112
31113
31207
31249
31271
31276
31325
31361
31386
31433
31584
31768
31800
31802
31804
31805
31806
31807
31808
31901
31902
31913
31921
31922
32035
32134
32181
32262
32263
32268
32282
32344
32349
32369
32400
32802
33062
33108
33118
33137
33236
33362
33407
33457
33458
33682
33791
33812
33814
34003
34219
34293
34432
34475
34493
34494
34557
34561
34632
34659
34706
34711
34774
34776
34777
34778
34785
34814
34849
34850
35027
35028
35031
35042
35241
35271
35358
35440
35633
35644
35651
35750
35759
35824
35978
36006
36009
36096
36134
36228
36340
36341
36361
36439
36453
36508
36509
36589
36688
36889
36947
36988
37052
37057
37063
37135
37354
37653
37758
37759
37913
38146
38337
38399
38416
38561
38733
38734
38736
38754
38756
38757
38845
39020
39223
39274
39293
39375
39376
39424
39520
39522
39556
39557
39574
39579
39582
39583
39586
39637
39821
40481
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 370, in connect
    ssl_context=context)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\ssl_.py", line 355, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 853, in _create
    self.do_handshake()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ConnectionAbortedError: [WinError 10053] Программа на вашем хост-компьютере разорвала установленное подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 370, in connect
    ssl_context=context)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\ssl_.py", line 355, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 853, in _create
    self.do_handshake()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionAbortedError(10053, 'Программа на вашем хост-компьютере разорвала установленное подключение', None, 10053, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\evroopt.py", line 121, in <module>
    a=Order()
  File "C:\Python34\evroopt.py", line 13, in __init__
    self.url = self.create_product_db()
  File "C:\Python34\evroopt.py", line 33, in create_product_db
    result = requests.get(url).text
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionAbortedError(10053, 'Программа на вашем хост-компьютере разорвала установленное подключение', None, 10053, None))
>>> 
